Repository woowa-techcamp-2020/todo-14, pull requests merged in 2020-07, with the labels that each got.

#1 Config
  .eslintrc.js
  .gitignore
  .prettierrc
  .vscode/settings.json
  babel.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/client/index.html
  src/client/index.js
  src/server/app.ts
  src/server/main.ts
  tsconfig.json
  webpack.config.js
Labels: config

#14 types: db 스키마 기반의 타입 생성
  src/types/activity.d.ts
  src/types/board.d.ts
  src/types/card.d.ts
  src/types/column.d.ts
  src/types/user.d.ts
Labels: types

#15 refactor(types): database schema
  src/types/activity.d.ts
  src/types/board.d.ts
  src/types/card.d.ts
  src/types/column.d.ts
  src/types/schema/activity.d.ts
  src/types/schema/board.d.ts
  src/types/schema/card.d.ts
  src/types/schema/column.d.ts
  src/types/schema/ownership.d.ts
  src/types/schema/user.d.ts
  src/types/user.d.ts
Labels: refactor, types

#16 feat: create api directory structure and skeleton
  src/server/api/index.ts
  src/server/app.ts
Labels: api, feature

#26 feat: create db related modules
  .gitignore
  package-lock.json
  package.json
  src/config/index.example.ts
  src/server/modules/connection.ts
  src/server/modules/query.ts
Labels: database, feature, types

#28 feat: column CRUD and get a board data
  src/server/api/create-a-column.ts
  src/server/api/get-a-board-data.ts
  src/server/api/index.ts
  src/server/api/modify-a-column.ts
  src/server/api/remove-a-column.ts
  src/server/modules/connection.ts
  src/server/modules/escape.ts
Labels: api, backend

#29 feat: initialize the main page layout
  src/client/index.html
  src/client/main.ts
  src/client/pages/index.html
  src/client/styles/_variables.scss
  src/client/styles/globalstyle.scss
  src/client/styles/page.scss
  tsconfig.json
  webpack.config.js
Labels: feature, front

#31 feat: card CRUD and 필요한 데이터를 받아 첫 화면을 출력함
  .gitignore
  public/fonts/Icons/Icons-Regular.eot
  public/fonts/Icons/Icons-Regular.ttf
  public/fonts/Icons/Icons-Regular.woff
  public/fonts/Icons/Icons-Regular.woff2
  public/fonts/Inter/Inter-Bold.woff
  public/fonts/Inter/Inter-Bold.woff2
  public/fonts/Inter/Inter-ExtraBold.woff
  public/fonts/Inter/Inter-ExtraBold.woff2
  public/fonts/Inter/Inter-Medium.woff
  public/fonts/Inter/Inter-Medium.woff2
  public/fonts/Inter/Inter-Regular.woff
  public/fonts/Inter/Inter-Regular.woff2
  public/fonts/Inter/Inter-SemiBold.woff
  public/fonts/Inter/Inter-SemiBold.woff2
  public/fonts/NotoSansKR/NotoSansKR-Black.woff
  public/fonts/NotoSansKR/NotoSansKR-Black.woff2
  public/fonts/NotoSansKR/NotoSansKR-Bold.woff
  public/fonts/NotoSansKR/NotoSansKR-Bold.woff2
  public/fonts/NotoSansKR/NotoSansKR-DemiLight.woff
  public/fonts/NotoSansKR/NotoSansKR-DemiLight.woff2
  public/fonts/NotoSansKR/NotoSansKR-Light.woff
  public/fonts/NotoSansKR/NotoSansKR-Light.woff2
  public/fonts/NotoSansKR/NotoSansKR-Medium.woff
  public/fonts/NotoSansKR/NotoSansKR-Medium.woff2
  public/fonts/NotoSansKR/NotoSansKR-Regular.woff
  public/fonts/NotoSansKR/NotoSansKR-Regular.woff2
  public/fonts/NotoSansKR/NotoSansKR-Thin.woff
  public/fonts/NotoSansKR/NotoSansKR-Thin.woff2
  src/client/api/create-a-card.ts
  src/client/api/get-a-board-data.ts
  src/client/api/get-boards-list.ts
  src/client/api/modify-a-card.ts
  src/client/api/remove-a-card.ts
  src/client/main.ts
  src/client/pages/index.html
  src/client/scripts/card-handlers/create-a-card-handlers.ts
  src/client/scripts/card-handlers/index.ts
  src/client/scripts/card-handlers/modify-a-card-handlers.ts
  src/client/scripts/card-handlers/remove-a-card-handlers.ts
  src/client/scripts/card.ts
  src/client/scripts/column.ts
  src/client/scripts/get-data-id.ts
  src/client/scripts/html-generator.ts
  src/client/scripts/init.ts
  src/client/styles/fonts.scss
  src/client/styles/globalstyle.scss
  src/client/styles/icons.scss
  src/client/styles/page.scss
  src/client/utils/content-parser.ts
  src/client/utils/event-collector.ts
  src/server/api/create-a-card.ts
  src/server/api/create-a-column.ts
  src/server/api/get-a-board-data.ts
  src/server/api/get-boards-list.ts
  tsconfig.json
  webpack.config.js
Labels: feature:card, front

#32 Feat/client/column
  src/client/main.ts
  src/client/scripts/column.ts
  src/client/scripts/drag-and-drop.ts
  src/client/styles/globalstyle.scss
  src/client/styles/page.scss
  webpack.config.js
Labels: feature, feature:column, front

#34 Feat/client/column
  src/client/scripts/column.ts
  src/client/scripts/drag-and-drop.ts
  src/client/scripts/html-generator.ts
  src/server/api/create-a-column.ts
  src/server/api/get-a-board-data.ts
  src/server/api/modify-a-column.ts
  src/server/api/remove-a-column.ts
Labels: fix, refactor

#36 Feat/client/column
  src/client/main.ts
  src/client/scripts/card-dnd.ts
  src/client/styles/icons.scss
  src/client/styles/page.scss
  src/server/api/get-a-board-data.ts
  src/server/api/remove-a-column.ts
  src/server/modules/connection.ts
Labels: enhancement, front

#37 fix(card-dnd): correctly clear previous transform
  src/client/scripts/card-dnd.ts
Labels: fix, front

#39 Fix column creation process
  .eslintignore
  src/client/main.ts
  src/client/pages/index.html
  src/client/scripts/activity.ts
  src/client/scripts/card-dnd.ts
  src/client/scripts/column.ts
  src/client/styles/activity.scss
  src/client/styles/globalstyle.scss
  src/client/styles/page.scss
  src/server/api/create-a-column.ts
  src/server/api/get-a-board-data.ts
  src/server/api/modify-cards-order.ts
Labels: config, feature, fix

#44 Update column modifying process
  src/client/api/modify-a-column.ts
  src/client/scripts/column.ts
  src/client/styles/globalstyle.scss
  src/client/styles/page.scss
  src/server/api/get-a-board-data.ts
  src/server/api/modify-a-column.ts
Labels: enhancement, fix

#46 Endgame/jhaemin
  package-lock.json
  package.json
  src/client/main.ts
  src/client/modules/update-column-badge-count.ts
  src/client/pages/index.html
  src/client/scripts/activity.ts
  src/client/scripts/card-dnd.ts
  src/client/scripts/card-handlers/create-a-card-handlers.ts
  src/client/scripts/card-handlers/remove-a-card-handlers.ts
  src/client/scripts/color-scheme.ts
  src/client/scripts/html-generator.ts
  src/client/scripts/init.ts
  src/client/styles/_mixins.scss
  src/client/styles/_variables.scss
  src/client/styles/activity.scss
  src/client/styles/globalstyle.scss
  src/client/styles/page.scss
  src/server/api/create-a-column.ts
  src/server/api/modify-a-column.ts
  src/server/api/remove-a-column.ts
  src/server/modules/create-an-activity.ts
  webpack.config.js
Labels: enhancement, feature, fix
